#!/bin/sh
# $Id: buildnum_incr,v 1.1 1998/04/03 21:54:21 wylie Exp $
# automatically increment build number BUILD_NUM

USAGE="usage: $0 FILE"
DEF_FILE=make.config.local
TMP=.incr.tmp

while [ ! -z "$1" ]
do
  case "$1" in
    -*)
        echo "Unrecognized flag: $1"
        break
        ;;
    *)
        # first non-flag argument is the target (others silently ignored!)
        FILE=$1
        break
        ;;
  esac
  shift
done

# common bail-point for unknown flags and undefined file
if [ -z "$FILE" ]; then
    echo $USAGE
    exit 1
fi

if [ -f $FILE ]; then
    buildnumstr=`grep BUILD_NUM $FILE`
    if [ -z "$buildnumstr" ]; then
        echo "BUILD_NUM not found in file $FILE -- aborting!"
        exit
    fi

    # extract previous build number
    oldbuildnum=`echo $buildnumstr | awk -F-- '{print (substr($2,0,3))}'`
    newbuildnum=`echo $oldbuildnum | awk '{print int($1+1)}'`
    newbuildnum=`printf "%03d" $newbuildnum`
    sedcmd=/BUILD_NUM/s/$oldbuildnum/$newbuildnum/p
    sed -e $sedcmd $FILE > $TMP
    if [ $? -ne 0 ]; then
        echo "Aborting broken sed"
        exit 1
    fi
    echo "BUILDNUM=-$oldbuildnum->$newbuildnum"
    mv $TMP $FILE
else
    echo "$FILE does not exist -- but will be created with BUILD_NUM info!"
    echo "BUILD_NUM=-000" | tee $FILE
fi

exit 0
