#!/bin/sh
# $Id: files_PD,v 1.1 1998/04/22 20:34:35 wylie Exp $
# list (or otherwise examine) all Paradyn/DynInst executable/library files

SOS=sparc-sun-sunos4.1.3
SOL=sparc-sun-solaris2.4
X86=i386-unknown-solaris2.5
SP2=rs6000-ibm-aix4.1
HPX=hppa1.1-hp-hpux
WNT=i386-unknown-nt4.0

ALL_PLATFORMS="$SOL $X86 $SP2 $WNT"
ARCH_LIST=$PLATFORM

USAGE="usage: files_PD [-a] [-d] [-i|-t] [platform-list]\n\
   -a: consider all supported platforms (instead of optional platform-list)\n\
   -d: use developer's repository (instead of default common repository)\n\
   -i: show ident_PD information (instead of default file listing)\n\
   -t: only list stale files (i.e., those not dated today)\n\
   platform-list: one or more platforms (defaults to only current platform)\n\
(current PLATFORM=$PLATFORM)\n\
(supported platforms: $ALL_PLATFORMS)\n"

P_ROOT="/p/paradyn"
ACTION="ls -loLF"
FILTER="cat"

tmp_file="/tmp/.tmp_file"

while [ -n "$1" ]
do
  case "$1" in
    "-a")
        # consider all (current) platforms
        ARCH_LIST=$ALL_PLATFORMS
        ;;
    "-d")
        # use developer's repository
        if [ -n "$USER" -a "$USER" != "paradyn" ]; then
            P_ROOT=$P_ROOT/development/$USER
        else
            echo "Sorry, no developer repository for USER=$USER"
        fi
        ;;
    "-i")
        # show ident info (assumes ident_PD is available)
        #ACTION=$P_ROOT/scripts/ident_PD
        IDENT_ACTION=true
        ;;
    "-t")
        # time to check or rebuild a stale file
        CHECK_FRESH=true
        ;;
    "-"*)
        #echo "Unrecognized flag: $1"
        PRINT_USAGE=true
        ;;
    *)
        # any non-flag arguments are platforms to consider
        ARCH_LIST=$*
        break
        ;;
  esac
  shift
done

# if necessary, patch WindowsNT shell PATH to recover some Unix utilities
if [ $PLATFORM = "i386-unknown-nt4.0" ]; then        
    NTPATH=//E/GNU/gnuwin32/b18/H-i386-cygwin32/bin
    #set ${PATH:=$NTPATH}
    PATH=$NTPATH
    P_ROOT="/$P_ROOT"
fi

if [ -n "$PRINT_USAGE" ]; then
    printf "$USAGE"
    exit 1
fi

if [ -n "$IDENT_ACTION" ]; then
    if [ $PLATFORM = "i386-unknown-nt4.0" ]; then
        ACTION="sh $P_ROOT/scripts/ident_PD"
    else
        ACTION="$P_ROOT/scripts/ident_PD"
    fi
elif [ -n "$CHECK_FRESH" ]; then
    TODAY=`date '+%b %e'`
    date '+%b %e' > $tmp_file
    TODAY="($TODAY)"
    FILTER="grep -v -f $tmp_file"
fi

ALL_UNX_EXES="paradyn paradynd igen rthist barChart phaseTable tableVisi tclVisi terrain"
ALL_WNT_EXES="paradynd.exe igen.exe"

ALL_API_OBJS="libdyninstRT.* libdyninstAPI.* libdyninstAPI_RT.*"
ALL_LIB_OBJS="libhist.a libpdutil.a libpdthread.a libvisi.a"
ALL_PRT_OBJS="DYNINSTendCode.o DYNINSTstartCode.o"
ALL_CPP_OBJS="libdyninstCP.*"
ALL_UNX_LIBS="$ALL_LIB_OBJS $ALL_API_OBJS"
ALL_WNT_LIBS="libpdutil.lib libdyninstRT.dll libdyninstAPI.lib libdyninstAPI_RT.dll"

for PLATFORM in $ARCH_LIST
do
    printf "\nPLATFORM=%-22s %8s\n" $PLATFORM "$TODAY"
    cd $P_ROOT/bin/$PLATFORM ; echo "[7m$P_ROOT/bin/$PLATFORM[m"
    case $PLATFORM in
      $WNT)
        $ACTION $ALL_WNT_EXES | $FILTER ;;
      *)
        $ACTION $ALL_UNX_EXES | $FILTER ;;
    esac
    cd $P_ROOT/lib/$PLATFORM ; echo "[7m$P_ROOT/bin/$PLATFORM[m"
    case $PLATFORM in
      $WNT)
        $ACTION $ALL_WNT_LIBS | $FILTER ;;
      $SP2)
        $ACTION $ALL_UNX_LIBS | $FILTER
        $ACTION $ALL_PRT_OBJS | $FILTER ;;
      *)
        $ACTION $ALL_UNX_LIBS | $FILTER ;;
    esac
done

if [ "$FILTER" != "cat" ]; then rm -f $tmp_file; fi

exit

